version: '3'
services:
  pbx:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
  proxy:
    build: ./kamailio/
    ports:
      - "5060:5060"
    depends_on:
      - db
  asterisk:
    build: ./asterisk/
    ports:
      - "5060:5060"
    depends_on:
      - db
  db:
    image: "postgres:9.6.3"
  proxy:
    build: ./kamailio/
    ports:
      - "5060:5060"
    depends_on:
      - db
